n1 = input("Digite uma palavra para descobrir as informações dela: ")
print("O tipo primitivo dela é", type(n1))
print(f"Ela possui apenas espaços? {n1.isspace()}")
print(f"Ela é númerica? {n1.isnumeric()}")
print(f"Ela é alfabética? {n1.isalpha()}")
print(f"Ela é alfanúmerico? {n1.isalnum()}")
print(f"Ela está em maiúsculas? {n1.isupper()}")
print(f"Ela está em minúsculas? {n1.islower()}")
print(f"Ela está em decimal? {n1.isdecimal()}")
print(f'Ela está capitalizada? {n1.istitle()}')
