print('Tabuada de vezes para treinar')
a = int(input('Digite um número para gerar a tabuada: '))
print(f'{a} x 1 = {a * 1}')
print(f'{a} x 2 = {a * 2}')
print(f'{a} x 3 = {a * 3}')
print(f'{a} x 4 = {a * 4}')
print(f'{a} x 5 = {a * 5}')
print(f'{a} x 6 = {a * 6}')
print(f'{a} x 7 = {a * 7}')
print(f'{a} x 8 = {a * 8}')
print(f'{a} x 9 = {a * 9}')